### ISSUE TITLE
Include more meta data in IGMGuesses output file

### ISSUE THREAD

**Issue by profxj** [pyigm/pyigm#111]
Include:

sl_dict['RA'] = [0.]*u.deg     # J2000, decimal degrees
sl_dict['DEC'] = [0.]*u.deg    # J2000, decimal degrees
sl_dict['zem'] = [0.]   # Emission redshift
sl_dict['Instrument'] = ['e.g. HST/COS/G130M PADDING']   # Telescope/Instrument/Grating
sl_dict['Creator'] = ['SOMEONES_NAME']   # Emission redshift

Facilitates Database generation

**Comment by ntejos** [comment]
Addressed in PR#112
