### ISSUE TITLE
Two small bugs in igmguesses.py

### ISSUE THREAD

**Issue by khrrubin** [pyigm/pyigm#166]
I've found success with pyigm_igmguesses over the last 24hrs by modifying igmguesses.py in two places (and apologies if this is too trivial; I'm a newbie):

out_dict['cmps'][key]['bfit'] = comp.attrib['b'].value
-->
out_dict['cmps'][key]['bfit'] = comp.attrib['b']

and 

self.velplot_widg.current_comp.attrib['b'] = igmg_dict['cmps'][key]['bfit']*u.km/u.s
-->
self.velplot_widg.current_comp.attrib['b'] = igmg_dict['cmps'][key]['bfit']

**Comment by profxj** [comment]
The handling of b-values in linetools was 
recently modified.  This may be a symptom of that.

I encourage you to submit a PR with these modifications.

**Comment by ntejos** [comment]
@khrrubin is right. In PR #167 this is addressed (I forgot to push this PR before).

**Comment by profxj** [comment]
Addressed.

**Comment by khrrubin** [comment]
Cool, thanks!
