### ISSUE TITLE
Pandas vs. Astropy Tables

### ISSUE THREAD

**Issue by profxj** [pyigm/pyigm#18]
I am recently enamored with Pandas tables.
Am seriously considering refactoring to use these 
where sensible (e.g. pyigm.fields).  Only obvious
downside is that they might not handle binary FITS
tables so seamlessly.

Please comment.

**Comment by mrafelski** [comment]
I'm still new at python so take this with a grain of salt. Pandas are what most people in industry use, so in that sense it will be better supported and have more features than astropy tables. Also, astropy does have functions to convert Pandas to astropy tables.  That being said, astropy tables has astronomy specific things, like working with units, ability to export to tex tables, and etc. Not handling binary FITS tables well would be a big downside I guess. I'll let more experienced python people weigh in.

**Comment by jnburchett** [comment]
I've gone straight from Numpy structured arrays to Astropy tables, so I cannot comment directly on Pandas.  However, I've been running my SDSS catalog cleaning/crossmatching using Astropy tables for the entire footprint for 4 days now, and some profiling has revealed that the 'add_row' method of astropy.table.Table is really bottlenecking things. Not sure your impetus for considering the switch, X, but if Pandas would perform better for low-level operations, I think we could convert back to Astropy at the higher levels for conveniences such as those Marc brings up.

**Comment by profxj** [comment]
I can’t say I know much about its performance, but 
I could see that running slow on Pandas too.

What I like are:
1.  People in the Industry use it and many other academics, i.e.
   I think it will continue to be well developed
2.  It treats Tables in a proper databasing way (e.g. SQL) and
   one can do SQL queries on their objects
3.  The built-in exploration tools are nice.
4.  I’ve not found the use of units in Astropy tables to be so helpful
   and my mix of using Table and QTable is getting to be a bit painful.
   I thought it was great at first, but I am finding it is as often annoying
   as it is helpful.

Cheers,

X

> On Feb 4, 2016, at 7:01 AM, jnburchett notifications@github.com wrote:
> 
> I've gone straight from Numpy structured arrays to Astropy tables, so I cannot comment directly on Pandas. However, I've been running my SDSS catalog cleaning/crossmatching using Astropy tables for the entire footprint for 4 days now, and some profiling has revealed that the 'add_row' method of astropy.table.Table is really bottlenecking things. Not sure your impetus for considering the switch, X, but if Pandas would perform better for low-level operations, I think we could convert back to Astropy at the higher levels for conveniences such as those Marc brings up. 
> 
> > On Feb 4, 2016, at 9:51 AM, mrafelski notifications@github.com wrote:
> > 
> > I'm still new at python so take this with a grain of salt. Pandas are what most people in industry use, so in that sense it will be better supported and have more features than astropy tables. Also, astropy does have functions to convert Pandas to astropy tables. That being said, astropy tables has astronomy specific things, like working with units, ability to export to tex tables, and etc. Not handling binary FITS tables well would be a big downside I guess. I'll let more experienced python people weigh in.
> > 
> > —
> > Reply to this email directly or view it on GitHub.
> > 
> > —
> > Reply to this email directly or view it on GitHub https://github.com/pyigm/pyigm/issues/18#issuecomment-179884755.
> 
> !DSPAM:826,56b367c8288664768349!

---

J. Xavier Prochaska
UCO/Lick Observatory
1156 High St.
UC Santa Cruz
Santa Cruz, CA 95064

http://www.ucolick.org/~xavier/
http://imps.ucolick.org/
http://www.qpqsurvey.org/
http://k1dm3.ucolick.org/
http://www.ucolick.org/~xavier/IDL/index.html
https://github.com/pyigm/pyigm
https://github.com/linetools/linetools

831-459-2135 (Direct)
831-459-2991 (UCO/Lick Main)
831-459-5244 (Fax)

**Comment by profxj** [comment]
There is yet another variant to consider:

http://xray.readthedocs.org/en/stable/

Built on Pandas.

I’ll bet I wind up here..

X

---

J. Xavier Prochaska
UCO/Lick Observatory
1156 High St.
UC Santa Cruz
Santa Cruz, CA 95064

http://www.ucolick.org/~xavier/
http://imps.ucolick.org/
http://www.qpqsurvey.org/
http://k1dm3.ucolick.org/
http://www.ucolick.org/~xavier/IDL/index.html
https://github.com/profxj/xastropy

831-459-2135 (Direct)
831-459-2991 (UCO/Lick Main)
831-459-5244 (Fax)

**Comment by nhmc** [comment]
I'm not really involved in pyigm, but here are my 2c anyway. 

I haven't used Pandas, but since it's widely used elsewhere, if seems fine to use it by default in pyigm. I believe there was discussion of using pandas tables in astropy, and this was rejected because pandas was seen as too big a dependency (also partly, I think, because astropy wanted to do their own thing). but given Pandas is installed by default with anaconda now, this isn't an issue any more. I would try to avoid adding dependencies that aren't widely-used though (like xray?), because it could cause installation issues for some people.

**Comment by profxj** [comment]
Having worked a bit more with these, I'm not as enamored.

astropy and numpy tables are what we have for now.
