### ISSUE TITLE
Try to load MWCGM, but 'AbsComponent' object has no attribute 'limits'

### ISSUE THREAD

**Issue by yzhenggit** [pyigm/pyigm#203]
Quick question, I'm trying to load in the MWCGM, but it says the error below. Any ideas on how to fix it? 

#### my input
from pyigm.cgm.galaxy import GalaxyCGM
mwcgm = GalaxyCGM()

#### The code return this error: 
/Users/Yong/anaconda3/lib/python3.5/site-packages/pyigm-0.1.dev0-py3.5.egg/pyigm/cgm/cgm.py:55: UserWarning: cgm.CGMAbsSys: Using Planck15 cosmology
  warnings.warn('cgm.CGMAbsSys: Using Planck15 cosmology')
/Users/Yong/anaconda3/lib/python3.5/site-packages/linetools-0.2.dev1306-py3.5.egg/linetools/lists/linelist.py:374: RuntimeWarning: divide by zero encountered in log10
  self._data['log(w*f)'] = np.log10(qm_strength)
Loading data.  This takes ~20s to build it all...
Loading abundances from Asplund2009
Abundances are relative by number on a logarithmic scale with H=12
Loading Richter+17 for CII, CIV, SiII, SiIII
---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
<ipython-input-1-d8457c36ab77> in <module>()
      1 from pyigm.cgm.galaxy import GalaxyCGM
      2 
----> 3 mwcgm = GalaxyCGM()

/Users/Yong/anaconda3/lib/python3.5/site-packages/pyigm-0.1.dev0-py3.5.egg/pyigm/cgm/galaxy.py in __init__(self, load, verbose, debug, **kwargs)
     51         if load:
     52             print("Loading data.  This takes ~20s to build it all...")
---> 53             self.load_coolgas()  # This needs to be first!
     54             self.load_hotgas()
     55 

/Users/Yong/anaconda3/lib/python3.5/site-packages/pyigm-0.1.dev0-py3.5.egg/pyigm/cgm/galaxy.py in load_coolgas(self)
    122             comps = ltiu.build_components_from_abslines(alines, chk_sep=False, chk_vel=False)
    123             # Limits
--> 124             vmin = np.min([icomp.limits.vmin.value for icomp in comps])
    125             vmax = np.max([icomp.limits.vmax.value for icomp in comps])
    126             # Instantiate

/Users/Yong/anaconda3/lib/python3.5/site-packages/pyigm-0.1.dev0-py3.5.egg/pyigm/cgm/galaxy.py in <listcomp>(.0)
    122             comps = ltiu.build_components_from_abslines(alines, chk_sep=False, chk_vel=False)
    123             # Limits
--> 124             vmin = np.min([icomp.limits.vmin.value for icomp in comps])
    125             vmax = np.max([icomp.limits.vmax.value for icomp in comps])
    126             # Instantiate

AttributeError: 'AbsComponent' object has no attribute 'limits'

**Comment by profxj** [comment]
Yup:

1. Update linetools
2.  Get on the halo_model branch of pyigm for now

**Comment by yzhenggit** [comment]
Yes, did both, but still the same error ...

**Comment by profxj** [comment]
odd that.  Let me explore further

**Comment by profxj** [comment]
I fear that I can't reproduce the error.

Did you clone pyigm from GitHub?

I'm pretty confident you have an install error
of some sort.  Only other option is you need
to be on Python 3.6 but that's unlikely.

**Comment by yzhenggit** [comment]
Yep, clone it from here directly. Will check my download process then.
