### ISSUE TITLE
Sort Component Widget by Redshift

### ISSUE THREAD

**Issue by jessicawerk** [pyigm/pyigm#34]
To improve ease of finding a specific component in order to edit/delete. List is currently ordered by the order in which lines are defined.

**Comment by ntejos** [comment]
I was half way through implementing this over the past hours, and finally came to the conclusion that ordering by redshift is not necessarily better than the current one. In fact, it may be confusing to see added lines appear all over the place in the Component Widget (I had that feeling myself at the testing stage). On the positive side of the current ordering is that you can keep track on what line was added first and last. In general, complex systems with multiple lines are added together (in a bunch) so they are still easy to find by looking at the component names (which include the redshift). Similarly, isolated weak HI systems are separated enough in redshift that are easy to spot too. My feeling is that this request is not worth the effort... .

ps. There may be a easier way to do this than what I tried, but I am not a expert on PyQt4 ...

**Comment by ntejos** [comment]
BTW, I will make IGMGuesses to select in the Component List Widget, the same component as selected by 'S' in the velocity plots. This will help to partially overcome the difficulty of finding the right component in the widget list.

**Comment by ntejos** [comment]
@jessicawerk please update pyigm making sure you have incorporated PR #42 (already in master branch). Will close this for now but feel free to re-open if you still consider it an issue.
