### ISSUE TITLE
Sort Strong Linelist by Ion, same as ISM linelist

### ISSUE THREAD

**Issue by jessicawerk** [pyigm/pyigm#35]
Users appreciate the custom sorting of the ISM linelist developed by Tejos. They would like the Strong linelist to be sorted similarly. It is now sorted by wavelength, which is fairly arbitrary for lineids/fitting purposes.

**Comment by ntejos** [comment]
This should have been addressed by PR #37. The default sorting is by abundance, ion_specie, strength of transition, slightly different than the order given by 'U' (update), but still convenient.
