### ISSUE TITLE
pyigm_igmguesses GUI undo button? 

### ISSUE THREAD

**Issue by jessicawerk** [pyigm/pyigm#38]
Is an "undo" button  possible? 

I.e. say you press a button, like "d", but it deletes a component you didn't mean to delete. whoops. Rather than going back to find the deleted component and re-fit, perhaps there could be a key that would just undo the deletion? 

This happens somewhat often given the big difference between "d" and "D"

The undo delete would be the best implementation of this. 
Although occasionally I press "]" instead of "=" accidentally, and that's annoying to correct too. If there were an undo or "go back" functionality, it would make things easier. 
Not sure both situations can be covered in a single fix, though 

Thanks! 
Jess

**Comment by ntejos** [comment]
Hi Jess,

Thanks for these suggestions. Will see if I can address this issue by making a reliable undo option, but at this moment I am a bit clueless on how to implement it.

I totally agree that is annoying to recover a component accidentally deleted, and the only current way to do now is by actually fitting it again. With respect to accidentally panning with "]" though, is pretty easy to comeback to a similar stage as before by pressing "[" (i.e. panning back), or simply using space bar until reaching the desired redshift.

**Comment by profxj** [comment]
Yeah, this one sounds impossible to code.

**Comment by jessicawerk** [comment]
Well, then I guess I just gained a new appreciation for all the applications I use that do have "undo" features, then! 
We'll just try to be more careful about deleting the things we intend to delete.

**Comment by profxj** [comment]
One can have D changed to some other key. 

On July 21, 2016 1:45:52 PM PDT, Jessica Werk notifications@github.com wrote:

> Well, then I guess I just gained a new appreciation for all the
> applications I use that do have "undo" features, then! 
> We'll just try to be more careful about deleting the things we intend
> to delete. 
> 
> ---
> 
> You are receiving this because you commented.
> Reply to this email directly or view it on GitHub:
> https://github.com/pyigm/pyigm/issues/38#issuecomment-234378700
> 
> !DSPAM:826,5791348f21154252030832!

## 

Sent from my Android device with K-9 Mail. Please excuse my brevity.

**Comment by jessicawerk** [comment]
Or else... what if deleting component were a two keystroke affair: 
"dW" = delete component selected in widget
"dS" = delete component selected on screen. 
or you press "d" and a little thing pops up, and asks "do you want to delete the component in the widget or closest to your cursor on the screen...?"  Another option would be to just press "cancel" and not delete anything.

**Comment by profxj** [comment]
Can be made so.  So easy, I bet even you could it!  ;)

**Comment by jessicawerk** [comment]
Let's not get carried away now!

**Comment by ntejos** [comment]
I'll leave this one for Jess ;)

**Comment by profxj** [comment]
Closing
