### ISSUE TITLE
igmguesses GUI: profile line colors, and hiding fits? 

### ISSUE THREAD

**Issue by jessicawerk** [pyigm/pyigm#39]
All the fits are shown in a gray color over the data after you fit a component. 
Any chance we could color the fitted components according to the assigned reliability? 
i.e.? 

gray = no reliability yet
green = a
blue = b
red = c

Also, in some cases it would be useful to be able to press a button and have all the fitted lines disappear (momentarily) so you can really focus on some selected component. 

Thanks! 

Jess

**Comment by profxj** [comment]
Now this is one that we (@ntejos) can handle!

**Comment by ntejos** [comment]
Sure thing ;)

**Comment by ntejos** [comment]
Addressed in PR #41. Note that keystroke 'M' (for model) is used for toggle model on/off, and consequently keystroke 'F' (for full ISM) gives you the full ISM LineList. Keystroke 'P' toggle on/off colorful display ;)
