### ISSUE TITLE
Add logU posterior distribution extraction

### ISSUE THREAD

**Issue by cwotta** [pyigm/pyigm#67]
It would be useful to be able to extract a logU posterior distribution from the output of mcmc.py.  I was given a code that does this, but requires *.pkl output format (from mcmc.py -- which is a possibility, but is currently only an option, as the default is *.hdf5) and explicit calculation of the UVB spectrum at the desired redshift.

**Comment by profxj** [comment]
Did we get this done, @cwotta ?

**Comment by cwotta** [comment]
There's no reason to do this.  We can get it from the density distribution + mcmc.dens_to_logU() function.
