### ISSUE TITLE
Calculate z~0 corrections for peculiar motions

### ISSUE THREAD

**Issue by profxj** [pyigm/pyigm#72]
For example, a 'correct' impact parameter given z and coordinates.

**Comment by profxj** [comment]
Should we close this @jnburchett ?

**Comment by jnburchett** [comment]
I did implemented this for CGM objects, but I see that the correction is not in place for IgmGalaxyField objects, which is another place it may be needed.  Probably the right thing to do is to refactor the pyigm.cgm.utils.calc_rho() functions, which are somewhat duplicated in pyigm.field.igmfield.py and where the velocity correction is not implemented.

Thoughts on how to resolve this duplication?

**Comment by profxj** [comment]
Did we accomplish this @jnburchett ?

**Comment by jnburchett** [comment]
Yep, believe so!
    On Saturday, January 13, 2018, 8:59:20 AM EST, J. Xavier Prochaska <notifications@github.com> wrote:  
 
 
Did we accomplish this @jnburchett ?

**Comment by profxj** [comment]
Closing.
