### ISSUE TITLE
IGMGUESSES: H2 molecular lines.

### ISSUE THREAD

**Issue by ntejos** [pyigm/pyigm#77]
Make IGMGUESSES capable of fitting H2 molecular lines. May need to modify linetools' LineList a bit.

**Comment by ntejos** [comment]
Note to myself: try the new method AbsComponent.add_abslines_from_linelist() using H2 linelist.

**Comment by profxj** [comment]
Was this done @ntejos ?

**Comment by ntejos** [comment]
This was already done, to the level of adding the LineList for H2 molecular lines, but the way the lines are sorted and presented may need extra thinking/work. I'm closing this for now, but keeping in mind that full IGMGuesses capabilities for H2 lines may still be lacking.
