### ISSUE TITLE
Statistical sample not correct in DLA surveys from literature

### ISSUE THREAD

**Issue by mneeleman** [pyigm/pyigm#94]
When loading a DLASurvey from literature with the 'stat' sample e.g.,
`xq100=DLASurvey.load_XQ100(sample='stat')`
The output will show that _no_ DLAs were found:
`<IGMSurvey: nsys=0, type=DLA, ref=XQ-100, nsightlines=100>`
I think the issue is in DLASurvey line 440. 
`if np.abs(idla.zem-qsos['ZEM'][idx[qq]]) < zem_tol:`

Here the code is trying to compare the QSO emission from the QSOs table (i.e., the file pyigm_path+'/data/DLA/XQ-100/XQ100_zpath.fit') to the DLA table (i.e., pyigm_path+'/data/DLA/XQ-100/XQ100_abs.fit'). The latter however does not contain any information on the emission of the QSOs, so idla.zem=0 for all DLAs, and the conditional in the if statement is always False.

As a note; this redshift comparison is rather unnecessary anyway (at least for the literature sample). Indeed, it probably is causing more harm than good. If the wrong QSO was found by line 434:
`idx, d2d, d3d = match_coordinates_sky(dla_coord, qsos_coord, nthneighbor=1)`
then this does not mean at all that the DLA is not statistical. It just means that the wrong QSO was found.

**Comment by profxj** [comment]
Is it just XQ-100?  And what if you don't specify stat?

**Comment by profxj** [comment]
Addressed by PR #96 .
